INSERT INTO public."Comment"(comment_id,video_id,user_id,likes,dislikes,comment_text) VALUES (1,1,2,2,123,'ultrices vel augue vestibulum');
INSERT INTO public."Comment"(comment_id,video_id,user_id,likes,dislikes,comment_text) VALUES (2,2,3,5,444,'proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut');
INSERT INTO public."Comment"(comment_id,video_id,user_id,likes,dislikes,comment_text) VALUES (3,3,4,1,44,'curabitur in libero ut');
INSERT INTO public."Comment"(comment_id,video_id,user_id,likes,dislikes,comment_text) VALUES (4,4,1,2,41,'convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate');
INSERT INTO public."Comment"(comment_id,video_id,user_id,likes,dislikes,comment_text) VALUES (5,5,3,10,23,'est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi');
INSERT INTO public."Comment"(comment_id,video_id,user_id,likes,dislikes,comment_text) VALUES (6,2,1,23,21,'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula');
INSERT INTO public."Comment"(comment_id,video_id,user_id,likes,dislikes,comment_text) VALUES (7,3,4,21,23,'adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut');
INSERT INTO public."Comment"(comment_id,video_id,user_id,likes,dislikes,comment_text) VALUES (8,1,6,21,10,'amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor');
INSERT INTO public."Comment"(comment_id,video_id,user_id,likes,dislikes,comment_text) VALUES (9,3,6,34,12,'est lacinia nisi');
INSERT INTO public."Comment"(comment_id,video_id,user_id,likes,dislikes,comment_text) VALUES (10,2,1,21,31,'aliquam convallis nunc proin at turpis a pede posuere');